import { PRACTICE_TYPE } from "./practice-type";

export const EXERCISES_TITLES = {
    [PRACTICE_TYPE.WEIGHT_LOSS]: "PERDA DE PESO",
    [PRACTICE_TYPE.INCREASE_MUSCLE]: "GANHAR MASSA",
    [PRACTICE_TYPE.KEEP_CONDITION]: "MANTER MASSA"
  };